import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cormorant_Garamond, Noto_Serif_JP } from 'next/font/google';
import "./globals.css";

const notoserif = Noto_Serif_JP({
  variable: '--font-noto-serif',
  weight: ['400', '700'],
  display: 'swap',
  subsets: ['latin'], // ✅ これを追加！
  preload: false, // ✅ プリロードをオフにする
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<html lang="ja" className={`${geistSans.variable} ${geistMono.variable} ${notoserif.variable}`}>
  <body className="antialiased">
    {children}
  </body>
</html>
  );
}