import type { Metadata } from "next";
import { Cormorant_Garamond, Noto_Serif_JP } from 'next/font/google';
import "./globals.css";

const notoserif = Noto_Serif_JP({
  variable: '--font-noto-serif',
  weight: ['400', '700'],
  display: 'swap',
  subsets: ['latin'], // ✅ これを追加！
  preload: false, // ✅ プリロードをオフにする
});

const cormorant = Cormorant_Garamond({
  variable: '--font-cormorant',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" className={`${notoserif.variable} ${cormorant.variable}`}>
      <body>{children}</body>
    </html>
  );
}